import {
  Cpu,
  CircleDot,
  Cog,
  Car,
  Zap,
  TriangleAlert,
  Search,
  Thermometer,
  Gauge,
  Disc,
  GripHorizontal,
  Droplet,
  Ruler,
  Flame,
  ThermometerSun,
  Plug,
  Wind,
  BatteryFull,
  Route,
  Waypoints,
  ArrowLeftRight,
  Target,
  Link2,
  Circle,
  Power,
  GitBranch,
  SlidersHorizontal,
  CircleCheckBig,
  Handshake,
  Star,
  Phone,
  Wrench,
  Award,
  BadgeDollarSign,
  MapPin,
  Mail,
  Clock,
  ListChecks,
  DollarSign,
  Receipt,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

// Maps the Font Awesome class suffix (e.g. "wrench" from "fa-solid fa-wrench",
// the shape all icon data in src/lib/marketing.ts and the public pages is
// still stored as) to a lucide-react icon, so existing data doesn't need to
// change shape while we drop the Font Awesome CDN stylesheet.
const ICON_MAP: Record<string, LucideIcon> = {
  microchip: Cpu,
  "circle-dot": CircleDot,
  gear: Cog,
  "oil-can": Droplet,
  "car-side": Car,
  car: Car,
  bolt: Zap,
  "bolt-lightning": Zap,
  "triangle-exclamation": TriangleAlert,
  "magnifying-glass": Search,
  "temperature-high": Thermometer,
  "gauge-high": Gauge,
  "compact-disc": Disc,
  "grip-lines": GripHorizontal,
  droplet: Droplet,
  ruler: Ruler,
  "fire-flame-curved": Flame,
  "temperature-arrow-up": ThermometerSun,
  plug: Plug,
  wind: Wind,
  "car-burst": Droplet,
  "battery-full": BatteryFull,
  road: Route,
  "circle-nodes": Waypoints,
  "arrows-left-right": ArrowLeftRight,
  "arrows-to-dot": Target,
  link: Link2,
  circle: Circle,
  "power-off": Power,
  "diagram-project": GitBranch,
  sliders: SlidersHorizontal,
  "check-circle": CircleCheckBig,
  handshake: Handshake,
  star: Star,
  phone: Phone,
  wrench: Wrench,
  certificate: Award,
  "comment-dollar": BadgeDollarSign,
  "map-location-dot": MapPin,
  envelope: Mail,
  clock: Clock,
  "list-check": ListChecks,
  "dollar-sign": DollarSign,
  "file-invoice-dollar": Receipt,
  "shield-halved": ShieldCheck,
};

type Props = { icon: string; className?: string };

// `icon` is a legacy Font Awesome class string like "fa-solid fa-wrench" —
// only the last token (the icon name) matters for the lookup.
export function Icon({ icon, className }: Props) {
  const key = icon.trim().split(/\s+/).pop()?.replace(/^fa-/, "") ?? "";
  const LucideIcon = ICON_MAP[key] ?? Wrench;
  return <LucideIcon className={className} aria-hidden="true" />;
}
